### ISSUE TITLE
Typo ;)

### ISSUE THREAD

**Issue by timothyallan** [klaude/eloquent-preferences#1]
line 179 In HasPreferences.php:

protected function hasPreferneceDefault($preference)

**Comment by klaude** [comment]
Hah, this is what using auto-completing editors gets me. :) I'll have that fixed up later today. Thanks for the report!

**Comment by klaude** [comment]
Thanks again for reporting. The typo is fixed in version 0.1.1. Please open more issues if you spot anything else!
