### ISSUE TITLE
Upgrade to Laravel 7.0

### ISSUE THREAD

**Issue by dionysiosarvanitis** [klaude/eloquent-preferences#6]
Upgrade to Laravel 7.0 please?

**Comment by klaude** [comment]
Can do. I'll see if there are any issues upgrading and update the requirements. Give me a few days to juggle this into my schedule. Thanks!

**Comment by dionysiosarvanitis** [comment]
ok, thanks a lot!

**Comment by klaude** [comment]
I just verified this installs and runs in Laravel 7. Give version 0.4.0 a try and let me know how it looks. Thanks!

**Comment by klaude** [comment]
Please let me know if this didn't work in your Laravel 7 project. Otherwise I'll close this issue out at the end of the day today. Thanks!

**Comment by dionysiosarvanitis** [comment]
Sorry, I'm not ready to test it yet since I'm starting a new project now on L 7.0. I'll let you know when I'm ready though.

**Comment by klaude** [comment]
No worries! Thanks for getting back to me. I'll leave this open for a week or so then, and I'll close it if I don't hear back from you.

**Comment by klaude** [comment]
No news is good news! I'm going to close this out. Please open another issue if you're seeing any issues with Laravel 7. Thanks!
