### ISSUE TITLE
Laravel 8.0 support

### ISSUE THREAD

**Issue by mbalandis** [klaude/eloquent-preferences#8]
Would be great if you release a tested version for Laravel ^8.0

I have forked and just bumped the version: 
https://github.com/sharpstream/eloquent-preferences/blob/laravel8-support/composer.json

Don't seem to have any issues but of course you may need run phpunit.

**Comment by klaude** [comment]
Thanks for the reminder, @mbalandis! I'll double check Laravel's release notes to look for gotchas and get Travis testing in Laravel 8. I'll shout out here when there's a new release with Laravel 8 support.

**Comment by klaude** [comment]
Thanks for waiting! I've tagged v0.5.0 with composer support for Laravel 8. Please give it a go and let me know how it looks. 

I didn't see any gotchas that would break things, but I may try to get Laravel 7's custom casts working in this. Gimme a bit on that one.

**Comment by mbalandis** [comment]
@klaude All seems to be good with v0.5.0. Thanks for an update!

**Comment by dionysiosarvanitis** [comment]
Thanks!

**Comment by klaude** [comment]
Awesome! I'll close this out. Enjoy!
